spring:
  datasource:
    url: jdbc:mysql://minnan.site:3306/rental?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: Minnan
    password: minnan
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000

  redis:
    host: minnan.site
    port: 6379
    database: 1
    password: minnan

server:
  port: 8101

jwt:
  header: Authorization
  expiration: 604800
  scret: min107

logging:
  file:
    name: ./logs/rental/rental.log

mybatis-plus:
  mapper-locations: /site/minnan/rental/domain/mapper/*.xml
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

aliyun:
  bucketName: link-server
  baseUrl: http://minnan.site:2000
  receiptFolder: receipt
  utilityFolder: utility